spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/startup_app}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:3675}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


seoul.api.key=${SEOUL_API_KEY:73616f4a52716b72333763706f4158}

# AWS S3 \uC124\uC815
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region=ap-northeast-2
cloud.aws.s3.bucket=flood-report-sup2
